// <auto-generated />
using System;
using System.Collections.Generic;
using Application.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Application.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260308203525_AddRefreshToken")]
    partial class AddRefreshToken
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Domain.Entities.CasoDePrueba", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Entrada")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("EsOculto")
                        .HasColumnType("boolean");

                    b.Property<Guid>("ProblemaId")
                        .HasColumnType("uuid");

                    b.Property<string>("SalidaEsperada")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("ProblemaId");

                    b.ToTable("CasosDePrueba");
                });

            modelBuilder.Entity("Domain.Entities.DetalleEnvio", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("CasoDePruebaId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("EnvioId")
                        .HasColumnType("uuid");

                    b.Property<int?>("Memoria")
                        .HasColumnType("integer");

                    b.Property<float?>("Tiempo")
                        .HasColumnType("real");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Veredicto")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("CasoDePruebaId");

                    b.HasIndex("EnvioId");

                    b.ToTable("DetalleEnvios");
                });

            modelBuilder.Entity("Domain.Entities.Envio", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("CodigoFuente")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("EntradaEstandar")
                        .HasColumnType("text");

                    b.Property<int>("LenguajeId")
                        .HasColumnType("integer");

                    b.Property<Guid?>("ProblemaId")
                        .HasColumnType("uuid");

                    b.Property<string>("Token")
                        .HasColumnType("text");

                    b.Property<Guid?>("UsuarioId")
                        .HasColumnType("uuid");

                    b.Property<string>("VeredictoGlobal")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("ProblemaId");

                    b.HasIndex("UsuarioId");

                    b.ToTable("Envios");
                });

            modelBuilder.Entity("Domain.Entities.Lenguaje", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("CodigoJudge0")
                        .HasColumnType("integer");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.ToTable("Lenguajes");
                });

            modelBuilder.Entity("Domain.Entities.Problema", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("EsEliminado")
                        .HasColumnType("boolean");

                    b.Property<int>("LimiteMemoria")
                        .HasColumnType("integer");

                    b.Property<float>("LimiteTiempo")
                        .HasColumnType("real");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Problemas");
                });

            modelBuilder.Entity("Domain.Entities.Usuario", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Apellidos")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Correo")
                        .HasColumnType("text");

                    b.Property<bool>("EstaActivo")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("FechaRegistro")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("RefreshToken")
                        .HasColumnType("text");

                    b.Property<DateTime?>("RefreshTokenExpiracion")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Rol")
                        .HasColumnType("integer");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("UserName")
                        .IsUnique();

                    b.ToTable("Usuarios");
                });

            modelBuilder.Entity("Domain.Entities.CasoDePrueba", b =>
                {
                    b.HasOne("Domain.Entities.Problema", "Problema")
                        .WithMany("CasosDePrueba")
                        .HasForeignKey("ProblemaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Problema");
                });

            modelBuilder.Entity("Domain.Entities.DetalleEnvio", b =>
                {
                    b.HasOne("Domain.Entities.CasoDePrueba", "CasoDePrueba")
                        .WithMany()
                        .HasForeignKey("CasoDePruebaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Domain.Entities.Envio", "Envio")
                        .WithMany("DetalleEnvios")
                        .HasForeignKey("EnvioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CasoDePrueba");

                    b.Navigation("Envio");
                });

            modelBuilder.Entity("Domain.Entities.Envio", b =>
                {
                    b.HasOne("Domain.Entities.Problema", "Problema")
                        .WithMany("Envios")
                        .HasForeignKey("ProblemaId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Domain.Entities.Usuario", "Usuario")
                        .WithMany("Envios")
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Problema");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("Domain.Entities.Usuario", b =>
                {
                    b.OwnsOne("Domain.Entities.MetadatosUsuario", "Metadatos", b1 =>
                        {
                            b1.Property<Guid>("UsuarioId")
                                .HasColumnType("uuid");

                            b1.Property<string>("Departamento")
                                .HasColumnType("text");

                            b1.Property<string>("FotoUrl")
                                .HasColumnType("text");

                            b1.PrimitiveCollection<List<string>>("Integrantes")
                                .HasColumnType("text[]");

                            b1.Property<string>("NombreEquipo")
                                .HasColumnType("text");

                            b1.Property<string>("Pais")
                                .HasColumnType("text");

                            b1.Property<string>("Universidad")
                                .HasColumnType("text");

                            b1.HasKey("UsuarioId");

                            b1.ToTable("Usuarios");

                            b1.ToJson("Metadatos");

                            b1.WithOwner()
                                .HasForeignKey("UsuarioId");
                        });

                    b.Navigation("Metadatos")
                        .IsRequired();
                });

            modelBuilder.Entity("Domain.Entities.Envio", b =>
                {
                    b.Navigation("DetalleEnvios");
                });

            modelBuilder.Entity("Domain.Entities.Problema", b =>
                {
                    b.Navigation("CasosDePrueba");

                    b.Navigation("Envios");
                });

            modelBuilder.Entity("Domain.Entities.Usuario", b =>
                {
                    b.Navigation("Envios");
                });
#pragma warning restore 612, 618
        }
    }
}
