// <auto-generated />
using System;
using Application.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Application.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Domain.Entities.CasoDePrueba", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Entrada")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("EsOculto")
                        .HasColumnType("boolean");

                    b.Property<Guid>("ProblemaId")
                        .HasColumnType("uuid");

                    b.Property<string>("SalidaEsperada")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("ProblemaId");

                    b.ToTable("CasosDePrueba");
                });

            modelBuilder.Entity("Domain.Entities.DetalleEnvio", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("CasoDePruebaId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("EnvioId")
                        .HasColumnType("uuid");

                    b.Property<int?>("Memoria")
                        .HasColumnType("integer");

                    b.Property<float?>("Tiempo")
                        .HasColumnType("real");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Veredicto")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("CasoDePruebaId");

                    b.HasIndex("EnvioId");

                    b.ToTable("DetalleEnvios");
                });

            modelBuilder.Entity("Domain.Entities.Envio", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("CodigoFuente")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("EntradaEstandar")
                        .HasColumnType("text");

                    b.Property<int>("LenguajeId")
                        .HasColumnType("integer");

                    b.Property<Guid?>("ProblemaId")
                        .HasColumnType("uuid");

                    b.Property<string>("Token")
                        .HasColumnType("text");

                    b.Property<string>("VeredictoGlobal")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("ProblemaId");

                    b.ToTable("Envios");
                });

            modelBuilder.Entity("Domain.Entities.Lenguaje", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("CodigoJudge0")
                        .HasColumnType("integer");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.ToTable("Lenguajes");
                });

            modelBuilder.Entity("Domain.Entities.Problema", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("EsEliminado")
                        .HasColumnType("boolean");

                    b.Property<int>("LimiteMemoria")
                        .HasColumnType("integer");

                    b.Property<float>("LimiteTiempo")
                        .HasColumnType("real");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.HasKey("Id");

                    b.ToTable("Problemas");
                });

            modelBuilder.Entity("Domain.Entities.CasoDePrueba", b =>
                {
                    b.HasOne("Domain.Entities.Problema", "Problema")
                        .WithMany("CasosDePrueba")
                        .HasForeignKey("ProblemaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Problema");
                });

            modelBuilder.Entity("Domain.Entities.DetalleEnvio", b =>
                {
                    b.HasOne("Domain.Entities.CasoDePrueba", "CasoDePrueba")
                        .WithMany()
                        .HasForeignKey("CasoDePruebaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Domain.Entities.Envio", "Envio")
                        .WithMany("DetalleEnvios")
                        .HasForeignKey("EnvioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CasoDePrueba");

                    b.Navigation("Envio");
                });

            modelBuilder.Entity("Domain.Entities.Envio", b =>
                {
                    b.HasOne("Domain.Entities.Problema", "Problema")
                        .WithMany("Envios")
                        .HasForeignKey("ProblemaId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Problema");
                });

            modelBuilder.Entity("Domain.Entities.Envio", b =>
                {
                    b.Navigation("DetalleEnvios");
                });

            modelBuilder.Entity("Domain.Entities.Problema", b =>
                {
                    b.Navigation("CasosDePrueba");

                    b.Navigation("Envios");
                });
#pragma warning restore 612, 618
        }
    }
}
